artifact_location: file:///C:/Users/shahj/OneDrive/Desktop/Projects/Final-Retail-Sales-Forecasting-main/mlruns_tracking/573707369134844674
creation_time: 1727578157595
experiment_id: '573707369134844674'
last_update_time: 1727578157595
lifecycle_stage: active
name: Retail Sales Forecasting
