artifact_uri: file:///C:/Users/shahj/OneDrive/Desktop/Projects/Final-Retail-Sales-Forecasting-main/mlruns_tracking/573707369134844674/adac4e30f5394197af327fef9daddf7b/artifacts
end_time: 1727578236367
entry_point_name: ''
experiment_id: '573707369134844674'
lifecycle_stage: active
run_id: adac4e30f5394197af327fef9daddf7b
run_name: RF_n_estimators_50
run_uuid: adac4e30f5394197af327fef9daddf7b
source_name: ''
source_type: 4
source_version: ''
start_time: 1727578228496
status: 3
tags: []
user_id: shahj
