artifact_location: file:///C:/Users/shahj/OneDrive/Desktop/Projects/Final-Retail-Sales-Forecasting-main/mlruns_tracking/0
creation_time: 1727578157579
experiment_id: '0'
last_update_time: 1727578157579
lifecycle_stage: active
name: Default
